/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.xml.parsers.ParserConfigurationException;

/**
 *
 * @author amiid
 */
public class Window extends javax.swing.JFrame {
    
    CurrencyData cd = new CurrencyData();
    /**
     * Creates new form Window
     */
    public Window(){
        initComponents();
        setComboBox();
        
    }

    private void setComboBox(){
        try {
            cd.readFromFile();
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(String c:cd.getCurrency()){
            this.currencyComboBox.addItem(c);
        }
        //this.currencyComboBox.setSelectedIndex(-1);
    }
    
    private void calculate(){
        try{
            float Euro = Float.parseFloat(this.valueInEuro.getText());
            this.resultTextField.setText(cd.getResult(Euro, 
                this.currencyComboBox.getSelectedItem().toString()));
        }catch (NumberFormatException  e) {
            this.resultTextField.setText("Wrong Euro Value!");
        }catch(NullPointerException e){
            this.resultTextField.setText("Can't load XML file!");
        }
    }
    
    private void CorrectingValueInEuro(){
        this.valueInEuro.setText(this.valueInEuro.getText().replace(",", "."));
        this.valueInEuro.setText(this.valueInEuro.getText().replace("-", ""));
        this.valueInEuro.setText(this.valueInEuro.getText().trim());
        if (this.valueInEuro.getText().isEmpty()) {
            this.valueInEuro.setText("0");
        }
        if(this.valueInEuro.getText().length()>1&&
                this.valueInEuro.getText().charAt(0)=='0'){
            this.valueInEuro.setText(this.valueInEuro.
                    getText().replaceFirst("0", ""));
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valueInEuro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        currencyComboBox = new javax.swing.JComboBox<>();
        resultTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Currency Calculator");
        setResizable(false);

        jLabel1.setText("EURO:");

        valueInEuro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valueInEuro.setText("1");
        valueInEuro.setToolTipText("Enter Value");
        valueInEuro.setMinimumSize(new java.awt.Dimension(64, 222));
        valueInEuro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valueInEuroKeyReleased(evt);
            }
        });

        jLabel2.setText("Select Currency:");

        currencyComboBox.setSelectedIndex(-1);
        currencyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyComboBoxActionPerformed(evt);
            }
        });

        resultTextField.setEditable(false);
        resultTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueInEuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addComponent(currencyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultTextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueInEuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currencyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyComboBoxActionPerformed
        // TODO add your handling code here:
        calculate();
    }//GEN-LAST:event_currencyComboBoxActionPerformed

    private void valueInEuroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valueInEuroKeyReleased
        // TODO add your handling code here:
        CorrectingValueInEuro();
        calculate();
    }//GEN-LAST:event_valueInEuroKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> currencyComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JTextField valueInEuro;
    // End of variables declaration//GEN-END:variables
}
